apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: aws-iam-role
spec:
  runInterval: 5m
  timeout: 1m
  extraAnnotations:
    iam.amazonaws.com/role: "arn:aws:iam::000000000000:role/kubernetes-example-role" # Replace this value with your ARN
    iam.amazonaws.com/external-id: <role-external-id> # Use this if kube2iam is using external-id for roles
  podSpec:
    containers:
    - name: main
      image: ghcr.io/mmogylenko/khcheck-aws-iam-role:latest
      imagePullPolicy: IfNotPresent
      env:
        - name: TARGET_ARN
          value: "arn:aws:iam::000000000000:role/kubernetes-example-role" # Replace this value with your ARN
        - name: DEBUG
          value: "1"
        - name: NODE_NAME # Good to know which worker is failing
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
